
[versions]
# AndroidX
appcompat = "1.7.1"
documentfile = "1.1.0"
lifecycle-extensions = "2.2.0"
lifecycle-common-java8 = "2.10.0"
preference = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.4"

# Google
material = "1.13.0"

# Third Party
android-gradle-plugin = "8.13.1"
flexbox = "3.0.0"
flexfilter = "0.9-alpha"
glide = "5.0.5"
gson = "2.13.2"
leakcanary = "2.14"
shimmer = "0.5.0"
shizuku = "12.2.0"
tooltips = "1.1.1"

[libraries]
# AndroidX
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-common-java8" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# Google
material = { module = "com.google.android.material:material", version.ref = "material" }

# Third Party
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
flexfilter = { module = "com.github.aefyr.flexfilter:flexfilter", version.ref = "flexfilter" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
tooltips = { module = "com.tomergoldst.android:tooltips", version.ref = "tooltips" }
